"""Chatbot-style Streamlit frontend for the help-centre assistant.

Run with:

    streamlit run streamlit_app.py

Deliberately minimal: a chat box and answers, nothing else. It does not display
retrieved chunks or a sources table — the answer is still generated by the same
grounded pipeline (evidence gate, then citation-validated generation, refusing
anything the corpus doesn't cover), the citations are just not shown here. For
that detail, use `python rag.py ask --json` or the Flask UI (`python rag.py serve`).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

import streamlit as st

from ragchat.chunkers import available_strategies
from ragchat.config import Config
from ragchat.grounding import CITATION_RE
from ragchat.pipeline import RAGPipeline
from ragchat.store import StoreError

REPO_ROOT = Path(__file__).resolve().parent

st.set_page_config(page_title="Help-centre assistant", page_icon="💬", layout="centered")


@st.cache_resource(show_spinner=False)
def load_config() -> Config:
    return Config.load(REPO_ROOT / "config.yaml")


@st.cache_resource(show_spinner="Loading index…")
def load_pipeline(strategy: str) -> RAGPipeline:
    return RAGPipeline.open(load_config(), strategy=strategy)


ASSISTANT_NAME = "the billing-migration help-centre assistant"

# Small talk never touches the RAG pipeline — it isn't a factual claim to ground
# or refuse, so routing it through the evidence gate is the wrong tool. Each
# pattern must match the WHOLE message (after trimming punctuation), so a real
# question like "hi, what does ERR-4032 mean?" still goes to the pipeline.
_GREETING_RE = re.compile(
    r"^(hi+|hello+|hey+|hiya|yo|howdy|greetings|good\s*(morning|afternoon|evening|day)|sup|what'?s\s*up)$",
    re.IGNORECASE,
)
_HOW_ARE_YOU_RE = re.compile(r"^how('?s| is| are)?\s*(it\s*going|you\s*doing|u|you)\??$", re.IGNORECASE)
_THANKS_RE = re.compile(r"^(thanks|thank\s*you|thx|ty|cheers|appreciate\s*it)$", re.IGNORECASE)
_FAREWELL_RE = re.compile(r"^(bye|goodbye|see\s*ya|see\s*you|later|farewell|good\s*night)$", re.IGNORECASE)
_HELP_RE = re.compile(r"^(help|what\s*can\s*you\s*do|who\s*are\s*you)\??$", re.IGNORECASE)


def small_talk_reply(text: str) -> str | None:
    """A canned reply for greetings/thanks/farewells, or None for a real question."""
    stripped = text.strip().strip("!.,?").strip()
    if not stripped:
        return "Hi there! Ask me anything about the billing migration."
    if _GREETING_RE.match(stripped):
        return (
            f"Hello! I'm {ASSISTANT_NAME}. Ask me about payment errors, invoices, "
            "plan mapping, tax/VAT, or the API changes — I'll answer from the "
            "indexed articles, or tell you if something isn't covered."
        )
    if _HOW_ARE_YOU_RE.match(stripped):
        return "Doing well, thanks for asking! What can I help you with on the billing migration?"
    if _THANKS_RE.match(stripped):
        return "You're welcome! Let me know if you have another question."
    if _FAREWELL_RE.match(stripped):
        return "Goodbye! Come back anytime you have a billing-migration question."
    if _HELP_RE.match(stripped):
        return (
            f"I'm {ASSISTANT_NAME}. I answer questions about the billing migration — "
            "error codes, payment methods, invoices, plan mapping, tax/VAT validation, "
            "and API/webhook changes — using only the indexed articles. If something "
            "isn't in them, I'll say so instead of guessing."
        )
    return None


def strip_citations(text: str) -> str:
    """Drop the trailing [chunk_id] markers so the chat bubble reads like prose.

    The pipeline still validates every citation before the answer reaches here —
    this only affects what's displayed, not whether the answer was grounded.
    """
    cleaned = CITATION_RE.sub("", text)
    cleaned = re.sub(r"[ \t]+([.,;:!?])", r"\1", cleaned)
    cleaned = re.sub(r"[ \t]{2,}", " ", cleaned)
    return "\n".join(line.rstrip() for line in cleaned.splitlines()).strip()


config = load_config()
strategies = available_strategies()

with st.sidebar:
    st.header("Settings")
    default_index = strategies.index(config.chunking.default_strategy) if config.chunking.default_strategy in strategies else 0
    strategy = st.selectbox("Chunking strategy", strategies, index=default_index)

    try:
        pipeline = load_pipeline(strategy)
    except StoreError as exc:
        st.error(f"No index found for `{strategy}`.\n\nRun this first:\n\n```\npython rag.py ingest data/legacy_articles\npython rag.py ingest\n```")
        st.stop()

    areas = [""] + pipeline.retriever.distinct_values("product_area")
    product_area = st.selectbox("Product area", areas, format_func=lambda a: a or "All areas")

    st.divider()
    if st.button("Clear conversation", use_container_width=True):
        st.session_state.messages = []
        st.rerun()

st.title("💬 Help-centre assistant")
st.caption("Ask about the billing migration. I only answer from the indexed articles.")

if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

question = st.chat_input("Ask a question…")
if question:
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):
        canned = small_talk_reply(question)
        if canned is not None:
            reply = canned
            st.markdown(reply)
        else:
            with st.spinner("Thinking…"):
                filters = {"product_area": product_area} if product_area else None
                answer = pipeline.ask(question, filters=filters)
            reply = answer.text if answer.refused else strip_citations(answer.text)
            st.markdown(reply)

    st.session_state.messages.append({"role": "assistant", "content": reply})
