"""Turn an :class:`~ragchat.evaluation.EvaluationReport` into the deliverables.

Writes:

* ``results.md``           — the report, numbers generated from the actual run
* ``results/evaluation.json`` — every number in machine-readable form
* ``results/search_dump_<strategy>.md`` — search-only top-5 for all 8 questions

The narrative sections (which chunker ships, and the retrieval that embarrassed
us) are authored by hand in ``eval/writeup.md`` and embedded verbatim, so the
generated numbers and the human analysis never get mixed up with each other.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence

from .models import Answer, SearchHit

PREVIEW_CHARS = 150


def write_artifacts(report, questions: Dict[str, Any], out_dir: Path, repo_root: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "evaluation.json").write_text(
        json.dumps(report.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8"
    )
    if report.sweep:
        (out_dir / "sweep.json").write_text(json.dumps(report.sweep, indent=2), encoding="utf-8")

    for strategy_report in report.strategy_reports:
        dump = _search_dump(strategy_report)
        (out_dir / f"search_dump_{strategy_report.strategy}.md").write_text(dump, encoding="utf-8")

    results_path = repo_root / "results.md"
    results_path.write_text(_results_markdown(report, questions, repo_root), encoding="utf-8")
    return results_path


# --------------------------------------------------------------------------
# results.md
# --------------------------------------------------------------------------


def _results_markdown(report, questions: Dict[str, Any], repo_root: Path) -> str:
    cfg = report.config_summary
    lines: List[str] = []
    add = lines.append

    add("# Week 3 Task Set A — Results")
    add("")
    add(f"*Generated by `python rag.py eval` at {report.generated_at}. Every number below comes")
    add("from that run; nothing in the tables is hand-written.*")
    add("")
    add("| Setting | Value |")
    add("|---|---|")
    add(f"| Chunk size / overlap | {cfg['chunk_size']} / {cfg['chunk_overlap']} characters |")
    add(f"| Embedding | `{cfg['embedding']}`, {cfg['n_features']} hashed features, identical for both strategies |")
    add(f"| top_k | {cfg['top_k']} |")
    add(f"| Generation backend | `{cfg['generation_backend']}` (model: {cfg['generation_model']}) |")
    add(f"| Refusal thresholds | min_top_score {cfg['min_top_score']}, min_evidence_coverage {cfg['min_evidence_coverage']} |")
    add(f"| Question set | `{Path(cfg['questions_file']).name}`, committed before any retrieval ran |")
    add("")

    add("## 0. Ingest reality: what was actually indexed")
    add("")
    add("The historical corpus was **not** re-indexed. The two legacy articles that stand in for")
    add("the pre-existing index were ingested once; the six new articles were then **appended**.")
    add("Ingest is append-only because the embedding function is stateless (no fitted vocabulary),")
    add("so adding a drop cannot change the vectors already stored.")
    add("")
    add("| Strategy | Ingest event | Articles | Chunks added | Seconds |")
    add("|---|---|---|---|---|")
    for strategy, events in report.index_history.items():
        for event in events:
            add(
                f"| {strategy} | {event['label']} | {event['n_documents']} | "
                f"{event['n_chunks']} | {event['seconds']} |"
            )
    add("")

    # -- 1. the questions ---------------------------------------------
    add("## 1. The eight known-answer questions")
    add("")
    add("Written from the articles before any search was run (see the provenance note at the top")
    add("of `eval/questions.yaml` and the git history: the question set is committed in")
    add("`380b479`, before the retrieval code existed).")
    add("")
    add("| # | Question | Known-correct article | Section | Answer must appear as | Table row? |")
    add("|---|---|---|---|---|---|")
    for item in questions["answerable"]:
        gold = item["gold"]
        anchors = ", ".join(f"`{a}`" for a in item.get("must_contain", []))
        add(
            f"| {item['id']} | {item['question']} | {gold['article_id']} "
            f"({gold['source_file']}) | {gold.get('section', '')} | {anchors} | "
            f"{'yes' if item.get('depends_on_table_row') else 'no'} |"
        )
    add("")

    # -- 2. hit rates --------------------------------------------------
    add("## 2. Hit-in-top-5, both strategies, same eight questions")
    add("")
    add("**Scoring contract** (fixed before the first run): a question is a hit when at least one")
    add("of the top-5 chunks is from the gold article *and* contains every `must_contain` string.")
    add("The second condition is the point — it asks whether the answer survived chunking intact,")
    add("not merely whether the right document ranked.")
    add("")
    add("| Strategy | hit@5 | Table-row questions | Prose questions | Chunks in index | Mean chunk chars |")
    add("|---|---|---|---|---|---|")
    for sr in report.strategy_reports:
        prose = [r for r in sr.results if not r.depends_on_table_row]
        add(
            f"| `{sr.strategy}` | **{sr.n_hits}/{sr.n_questions}** | {sr.table_hits} | "
            f"{sum(1 for r in prose if r.hit)}/{len(prose)} | {sr.n_chunks} | {sr.mean_chunk_chars} |"
        )
    add("")
    add("### Secondary metric: self-contained hit@5")
    add("")
    add("**Disclosure on ordering.** The committed hit criterion above saturated at 8/8 for both")
    add("strategies and at every chunk size in the sweep, so on its own it does not discriminate.")
    add("It is reported unchanged. The metric below was added *after* seeing that saturation, and")
    add("is computed over the same eight questions and the same retrieval runs.")
    add("")
    add("A hit is **self-contained** when the answer-bearing chunk can be interpreted on its own:")
    add("if it contains table rows, the header row must be in the same chunk. A bare")
    add("`| ERR-4032 | ... | ... |` row is retrievable but does not tell an agent which cell is the")
    add("cause and which is the fix — which is precisely the property this week's chunker targets.")
    add("")
    add("| Strategy | self-contained hit@5 | Table-row questions | Answer-bearing chunks that lost their header |")
    add("|---|---|---|---|")
    for sr in report.strategy_reports:
        lost = sum(1 for r in sr.results if r.hit and not r.self_contained_hit)
        add(
            f"| `{sr.strategy}` | **{sr.n_self_contained}/{sr.n_questions}** | "
            f"{sr.table_self_contained} | {lost} |"
        )
    add("")
    add("### Per-question record")
    add("")
    header = "| # | Question | Gold article | " + " | ".join(f"`{sr.strategy}`" for sr in report.strategy_reports) + " |"
    add(header)
    add("|---|---|---|" + "---|" * len(report.strategy_reports))
    by_qid = {sr.strategy: {r.qid: r for r in sr.results} for sr in report.strategy_reports}
    for item in questions["answerable"]:
        qid = item["id"]
        cells = []
        for sr in report.strategy_reports:
            result = by_qid[sr.strategy][qid]
            if not result.hit:
                cells.append("MISS")
            elif result.self_contained_hit:
                cells.append(f"HIT @{result.hit_rank} (`{result.hit_chunk_id}`)")
            else:
                cells.append(
                    f"HIT @{result.hit_rank} (`{result.hit_chunk_id}`) — **header lost**"
                )
        add(f"| {qid} | {item['question'][:60]} | {item['gold']['article_id']} | " + " | ".join(cells) + " |")
    add("")
    add("`header lost` marks a hit under the committed criterion whose chunk failed the")
    add("self-contained check: the row was retrieved without the header row that labels its cells.")
    add("")

    add("### Every miss, with its diagnosis")
    add("")
    any_miss = False
    for sr in report.strategy_reports:
        for result in sr.results:
            if result.hit:
                continue
            any_miss = True
            add(f"- **`{sr.strategy}` / {result.qid}** — {result.question}")
            add(f"  - {result.diagnosis}")
            add(f"  - top-5 returned: {', '.join(h.chunk.chunk_id for h in result.hits) or '(nothing)'}")
    if not any_miss:
        add("- No misses for either strategy on this run.")
    add("")

    # -- 3. metadata filter --------------------------------------------
    demo = report.filter_demo
    add("## 3. Metadata filter changing retrieval")
    add("")
    add(f"Query: **{demo.question}**  ")
    add(f"Filter: `{demo.filters}`  ")
    add(f"Top-1 changed: **{demo.changed_top1}**")
    add("")
    add("The query is deliberately ambiguous across the corpus: the payments article documents a")
    add("10-day dunning retry window, the developer-api article documents a 24-hour webhook retry")
    add("window. Without a filter the payments answer wins; filtering to `developer-api` returns")
    add("the webhook answer instead.")
    add("")
    add("**Unfiltered**")
    add("")
    add(_hits_table(demo.unfiltered))
    add("")
    add(f"**Filtered — `{demo.filters}`**")
    add("")
    add(_hits_table(demo.filtered))
    add("")

    # -- 4. cited answers ----------------------------------------------
    add("## 4. Three answerable questions, answered with citations")
    add("")
    add("Each citation is checked twice: the `chunk_id` must resolve to a chunk that was actually")
    add("retrieved for that question, and the cited chunk must contain the known answer text.")
    add("")
    for check in report.answer_checks:
        add(f"### {check.qid} — {check.question}")
        add("")
        add("```text")
        add(check.answer.text.strip())
        add("```")
        add("")
        add("| Cited chunk_id | Resolves | Article | Source file | Section |")
        add("|---|---|---|---|---|")
        for citation in check.answer.citations:
            add(
                f"| `{citation.chunk_id}` | {'yes' if citation.resolved else 'NO'} | "
                f"{citation.article_id} | {citation.source_file} | {citation.section} |"
            )
        add("")
        add(
            f"- all citations resolve: **{check.citations_resolve}**; a cited chunk contains the "
            f"known answer: **{check.citation_supports_claim}** "
            f"(`{check.supporting_chunk_id}`)"
        )
        add("")

    # -- 5. refusals ----------------------------------------------------
    add("## 5. Three out-of-corpus questions, refused")
    add("")
    add("Refusal is forced, not suggested. The evidence gate runs **before** generation: when the")
    add("question's idf-weighted content is not present in the retrieved chunks, the pipeline")
    add("refuses and no generator is invoked at all.")
    add("")
    for answer in report.refusals:
        add(f"### {answer.question}")
        add("")
        add("```text")
        add(f"Q: {answer.question}")
        add("")
        add(answer.text.strip())
        add("")
        add(f"[refused: {answer.refusal_reason}]")
        add("```")
        add("")
        evidence = answer.diagnostics.get("evidence", {})
        if evidence:
            add(
                f"- idf-weighted coverage **{evidence.get('idf_weighted_coverage')}** vs threshold "
                f"{cfg['min_evidence_coverage']}; terms absent from the corpus: "
                f"`{evidence.get('missing_terms')}`"
            )
        add("")

    # -- 6. chunk-size sweep --------------------------------------------
    if report.sweep:
        add("## 6. Chunk-size comparison")
        add("")
        add("Same eight questions, same embedding, same top_k — only the chunk size changes.")
        add("")
        add("| Strategy | Chunk size | Overlap | Chunks | Mean chars | hit@5 | self-contained@5 | Table qs (self-contained) |")
        add("|---|---|---|---|---|---|---|---|")
        for row in report.sweep:
            add(
                f"| `{row['strategy']}` | {row['chunk_size']} | {row['chunk_overlap']} | "
                f"{row['n_chunks']} | {row['mean_chunk_chars']} | {row['hit_at_5']} | "
                f"**{row['self_contained_hit_at_5']}** | {row['table_questions_self_contained']} |"
            )
        add("")

    # -- 7. bonus --------------------------------------------------------
    if report.bonus:
        add("## 7. Bonus — precision vs completeness")
        add("")
        add(
            f"*Both probes run with the evidence gate relaxed to "
            f"{report.bonus[0].get('gate_relaxed_to')} (shipping value "
            f"{report.bonus[0].get('shipping_gate')}), because the bonus is about how complete "
            "each answer is once retrieval has happened, not about the gate.*"
        )
        add("")
        for probe in report.bonus:
            title = f"### {probe['id']} — {probe['question']}"
            add(title)
            add("")
            if probe["added_after_first_run"]:
                add("*Added after the first run — see the note in `eval/questions.yaml`. Not part of")
                add("any scored metric.*")
                add("")
            add(f"Context: top-{probe['context_chunks']} chunk(s).")
            add("")
            add(f"Known complete answer: {probe['known_answer'].strip()}")
            add("")
            for strategy, answer in probe["answers"].items():
                add(f"**`{strategy}`**")
                add("")
                add("```text")
                add(
                    answer["text"].strip()
                    if not answer["refused"]
                    else f"REFUSED — {answer['refusal_reason']}"
                )
                add("```")
                add("")

    # -- 8. hand-written analysis ----------------------------------------
    writeup = repo_root / "eval" / "writeup.md"
    if writeup.is_file():
        add(writeup.read_text(encoding="utf-8").strip())
        add("")

    add("---")
    add("")
    add("Raw artefacts: `results/evaluation.json`, `results/sweep.json`,")
    add("`results/search_dump_baseline.md`, `results/search_dump_structure-aware.md`.")
    add("")
    return "\n".join(lines)


def _hits_table(hits: Sequence[SearchHit]) -> str:
    rows = [
        "| Rank | Score | chunk_id | product_area | Article | Section | Preview |",
        "|---|---|---|---|---|---|---|",
    ]
    if not hits:
        rows.append("| — | — | (no matches) | — | — | — | — |")
        return "\n".join(rows)
    for hit in hits:
        chunk = hit.chunk
        rows.append(
            f"| {hit.rank} | {hit.score:.4f} | `{chunk.chunk_id}` | {chunk.product_area} | "
            f"{chunk.article_id} | {chunk.section} | {_preview(chunk.text)} |"
        )
    return "\n".join(rows)


def _preview(text: str, limit: int = PREVIEW_CHARS) -> str:
    flat = " ".join(text.split()).replace("|", "\\|")
    return flat[:limit] + ("…" if len(flat) > limit else "")


# --------------------------------------------------------------------------
# search-only dumps
# --------------------------------------------------------------------------


# --------------------------------------------------------------------------
# Week 4: failure labelling + before/after retrieval metrics
# --------------------------------------------------------------------------


def write_week4_artifacts(report, out_dir: Path, repo_root: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "week4_evaluation.json").write_text(
        json.dumps(report.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8"
    )
    results_path = repo_root / "results_week4.md"
    results_path.write_text(_week4_markdown(report, repo_root), encoding="utf-8")
    return results_path


def _week4_markdown(report, repo_root: Path) -> str:
    cfg = report.config_summary
    lines: List[str] = []
    add = lines.append

    add("# Week 4 Task Set A — Debugging Retrieval: Results")
    add("")
    add(f"*Generated by `python rag.py eval-failures` at {report.generated_at}. Every number below")
    add("comes from that run against the real index; nothing in the tables is hand-written.*")
    add("")
    add("| Setting | Value |")
    add("|---|---|")
    add(f"| Strategy (chunker) | `{cfg.get('strategy')}` |")
    add(f"| Scored at | hit-rate@{cfg.get('k')}, retrieval window inspected: top-{cfg.get('window')} |")
    add(f"| RRF constant (`rrf_k`) | {cfg.get('rrf_k')} |")
    add(f"| BM25 constants | k1={cfg.get('bm25_k1')}, b={cfg.get('bm25_b')} |")
    add(f"| Shipping retrieval mode (config.yaml) | `{cfg.get('shipping_retrieval_mode')}` |")
    add(f"| Question set | `{Path(cfg.get('questions_file', '')).name}` |")
    add("")

    add("## 0. What this measures")
    add("")
    add("Every question below was caught failing against the Week 3 shipping index — semantic-only")
    add("search over the hashed `lnc.ltc` vectors — **before** the hybrid retriever existed. Two")
    add("independent retrieval passes then run over every question: `semantic` (the Week 3 behaviour,")
    add("unchanged) and `hybrid` (semantic search and BM25 keyword search, fused by reciprocal rank")
    add("fusion). The pipeline answer shown as \"before\" is always generated under `semantic`, so the")
    add("failure label reflects what these questions actually did before this week's change.")
    add("")

    # -- 1. before/after headline numbers -------------------------------
    add("## 1. Before / after: hit-rate@3, recall@3, MRR")
    add("")
    add("| Metric | semantic (before) | hybrid (after) |")
    add("|---|---|---|")
    add(
        f"| hit-rate@3 | **{report.n_semantic_hits}/{report.n_questions}** "
        f"({report.semantic_hit_rate_at_3:.0%}) | **{report.n_hybrid_hits}/{report.n_questions}** "
        f"({report.hybrid_hit_rate_at_3:.0%}) |"
    )
    add(f"| recall@3 | {report.semantic_recall_at_3:.3f} | {report.hybrid_recall_at_3:.3f} |")
    add(f"| MRR@{cfg.get('window')} | {report.semantic_mrr:.3f} | {report.hybrid_mrr:.3f} |")
    add("")
    add(
        f"The one change — hybrid search — **fixed {report.n_fixed} of the "
        f"{report.n_questions - report.n_semantic_hits} originally-failing questions**, "
        f"and broke {report.n_broken} that used to pass. Recall@3 counts partial credit on the one"
    )
    add("question with a second required fact (`K3`), which is why it can move even when hit-rate@3")
    add("does not: see the per-question table below.")
    add("")

    # -- per-category breakdown -----------------------------------------
    add("### By category")
    add("")
    add("| Category | Questions | semantic hit@3 | hybrid hit@3 | Meaning |")
    add("|---|---|---|---|---|")
    meanings = {
        "keyword_dilution": "retrieval failure that hybrid search is expected to fix",
        "semantic_gap": "retrieval failure that hybrid search is **not** expected to fix",
        "generation_gate": "generation failure — not a retrieval problem at all",
    }
    for category, records in report.by_category().items():
        sem = sum(1 for r in records if r.semantic_hit3)
        hyb = sum(1 for r in records if r.hybrid_hit3)
        add(f"| `{category}` | {len(records)} | {sem}/{len(records)} | {hyb}/{len(records)} | {meanings.get(category, '')} |")
    add("")

    # -- 2. per-question inspection view ---------------------------------
    add("## 2. Inspection view: question, what was fetched, and the final answer")
    add("")
    add("Side by side for every question: the label the harness computed from evidence (not asserted")
    add("up front), what each retrieval mode actually returned, and the pipeline's answer before the")
    add("fix.")
    add("")
    for r in report.records:
        add(f"### {r.qid} ({r.category}) — {r.question}")
        add("")
        add(f"**Label: {r.label}**")
        add("")
        add(f"- semantic rank of the answer-bearing chunk: {r.semantic_rank!r}  (hit@3: {r.semantic_hit3})")
        add(f"- hybrid rank of the answer-bearing chunk: {r.hybrid_rank!r}  (hit@3: {r.hybrid_hit3})")
        add(f"- known-correct answer: {r.known_answer.strip()}")
        add("")
        add("**semantic top-3 fetched**")
        add("")
        add(_hits_table(r.semantic_hits[:3]))
        add("")
        add("**hybrid top-3 fetched**")
        add("")
        add(_hits_table(r.hybrid_hits[:3]))
        add("")
        add("**final answer (before the fix, semantic-only pipeline)**")
        add("")
        add("```text")
        if r.answer.refused:
            add(f"REFUSED — {r.answer.refusal_reason}")
        else:
            add(r.answer.text.strip())
        add("```")
        add("")

    # -- 3. what did NOT get fixed ----------------------------------------
    add("## 3. What the change did NOT fix")
    add("")
    still_failing = [r for r in report.records if not r.hybrid_hit3 and r.label.startswith("retrieval failure")]
    generation_failures = [r for r in report.records if r.label.startswith("generation failure")]
    broken = [r for r in report.records if r.broken_by_hybrid]

    add(f"**Still a retrieval failure under hybrid ({len(still_failing)}):**")
    add("")
    for r in still_failing:
        add(f"- `{r.qid}` ({r.category}) — {r.question}")
        add(f"  - semantic rank {r.semantic_rank!r} -> hybrid rank {r.hybrid_rank!r}, still outside the top-3")
    if not still_failing:
        add("- none")
    add("")

    add(f"**Generation failures, untouched by a retrieval-only fix by design ({len(generation_failures)}):**")
    add("")
    for r in generation_failures:
        add(f"- `{r.qid}` — {r.question}")
        add(
            f"  - retrieved correctly at rank {r.semantic_rank} under both modes; "
            f"the pipeline still answers: {'REFUSED — ' + str(r.answer.refusal_reason) if r.answer.refused else '(wrong answer, not refused)'}"
        )
    if not generation_failures:
        add("- none")
    add("")

    if broken:
        add(f"**Regressions — questions hybrid made worse ({len(broken)}):**")
        add("")
        for r in broken:
            add(f"- `{r.qid}` — semantic rank {r.semantic_rank!r} -> hybrid rank {r.hybrid_rank!r}")
        add("")

    # -- 4. hand-written analysis ------------------------------------------
    writeup = repo_root / "eval" / "week4_writeup.md"
    if writeup.is_file():
        add(writeup.read_text(encoding="utf-8").strip())
        add("")

    add("---")
    add("")
    add("Raw artefacts: `results/week4_evaluation.json`.")
    add("")
    return "\n".join(lines)


def _search_dump(strategy_report) -> str:
    lines = [
        f"# Search-only dump — `{strategy_report.strategy}`",
        "",
        f"Index namespace: `{strategy_report.namespace}` · {strategy_report.n_chunks} chunks · "
        f"mean {strategy_report.mean_chunk_chars} chars",
        "",
        "No generation is involved here: this is the raw top-5 for each of the eight questions.",
        "",
    ]
    for result in strategy_report.results:
        lines.append(f"## {result.qid} — {result.question}")
        lines.append("")
        lines.append(
            f"Gold: **{result.gold_article}** / {result.gold_section} · "
            f"must contain {result.must_contain} · "
            f"**{'HIT at rank ' + str(result.hit_rank) if result.hit else 'MISS'}**"
        )
        lines.append("")
        lines.append(f"Diagnosis: {result.diagnosis}")
        lines.append("")
        lines.append(_hits_table(result.hits))
        lines.append("")
    return "\n".join(lines)
